//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNFCRM_Chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATINFO
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IP { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public Nullable<bool> Q1 { get; set; }
        public Nullable<bool> Q2 { get; set; }
        public Nullable<bool> Q3 { get; set; }
        public Nullable<bool> Q4 { get; set; }
        public Nullable<bool> Q5 { get; set; }
        public Nullable<bool> Q6 { get; set; }
        public Nullable<bool> Q7 { get; set; }
        public Nullable<bool> Q8 { get; set; }
        public Nullable<bool> Q9 { get; set; }
        public Nullable<bool> Q10 { get; set; }
        public string ConsultingType { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
