//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNFCRM_Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERCARE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMERCARE()
        {
            this.CUSTOMERCAREDETAILs = new HashSet<CUSTOMERCAREDETAIL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public Nullable<System.DateTime> ConsultDate { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERCAREDETAIL> CUSTOMERCAREDETAILs { get; set; }
    }
}
