//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNFCRM_Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CONTRACTs = new HashSet<CONTRACT>();
            this.CUSTOMERCAREs = new HashSet<CUSTOMERCARE>();
            this.PRODUCTLINEs = new HashSet<PRODUCTLINE>();
            this.REQUIREPRODUCTs = new HashSet<REQUIREPRODUCT>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Job { get; set; }
        public string Company { get; set; }
        public string PreviousDesign { get; set; }
        public string PreviousFabric { get; set; }
        public string PreviousCompanyDesign { get; set; }
        public Nullable<double> PreviousPrice { get; set; }
        public string Note { get; set; }
        public Nullable<bool> PotentailCustomer { get; set; }
        public Nullable<int> ID_Consult { get; set; }
        public string CareAboutProduct { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        public virtual CUSTOMERCONSULTING CUSTOMERCONSULTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERCARE> CUSTOMERCAREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTLINE> PRODUCTLINEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUIREPRODUCT> REQUIREPRODUCTs { get; set; }
    }
}
