//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNFCRM_Chat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CP_CRMEntities : DbContext
    {
        public CP_CRMEntities()
            : base("name=CP_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHATINFO> CHATINFOes { get; set; }
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<CONTRACT> CONTRACTs { get; set; }
        public virtual DbSet<CONTRACTDETAIL> CONTRACTDETAILs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMERCONSULTING> CUSTOMERCONSULTINGs { get; set; }
        public virtual DbSet<MENSIZE> MENSIZEs { get; set; }
        public virtual DbSet<PRODUCTLINE> PRODUCTLINEs { get; set; }
        public virtual DbSet<REQUIREPRODUCT> REQUIREPRODUCTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WOMENSIZE> WOMENSIZEs { get; set; }
    }
}
